module.exports = {
  images: { 
    remotePatterns: [
      { protocol: "https", hostname: "uploads.strikinglycdn.com" },
      { protocol: "https", hostname: "static.wixstatic.com" },
    ],
  },
  i18n: {
    locales: [
      "en",
      "cy",
      "fr",
      "es",
      "bn",
      "ur",
      "ar",
      "pl",
      "ro",
      "fa",
      "sk",
      "gd",
      "prs",
      "so",
      "alb",
      "tr",
      "apd",
      "ti",
      "bg",
      "ps",
      "ua",
      "zh",
      "zh-CHT",
      "hu",
      "ru",
      "ckb",
      "pt",
    ],
    defaultLocale: "en",
  },
};
